--liquibase formatted sql

--changeset CREATE_PLANET:Rafael
CREATE TABLE PLANET (
	ID BINARY(16) NOT NULL,
	NAME VARCHAR(150) NOT NULL,
	CLIMATE VARCHAR(150) NOT NULL,
	TERRAIN VARCHAR(150) NOT NULL,
	POPULATION VARCHAR(80) NOT NULL DEFAULT 0,

	CONSTRAINT PK_PLANET PRIMARY KEY(ID),
	CONSTRAINT UK_PLANET_NAME UNIQUE(NAME)
);

