INSERT INTO PLANET (ID, NAME, CLIMATE, TERRAIN, POPULATION) VALUES (
	'AAAAAAAABBBBCCCCDDDD1234567890AB',
	'TEST 1',
	'Dry',
	'Sand',
	'20'
);

INSERT INTO PLANET (ID, NAME, CLIMATE, TERRAIN, POPULATION) VALUES (
	'0AAAAAAABBBBCCCCDDDD1234567890AB',
	'Another test',
	'Humid',
	'Mud',
	'0'
);

INSERT INTO PLANET (ID, NAME, CLIMATE, TERRAIN, POPULATION) VALUES (
	'00AAAAAABBBBCCCCDDDD1234567890AB',
	'Flame Planet',
	'Hot',
	'Stone',
	'unknown'
);

